---
- name: dev tools
  shell: yum groupinstall 'Development Tools' -y ; yum install zlib-devel pcre pcre-devel -y
  become: yes

- name: download nginx
  get_url: 
    url: "{{ nginx_download_url }}"
    dest: "/tmp"

- name: unarchive
  unarchive:
    src: "/tmp/nginx-{{ nginx_version }}.tar.gz"
    dest: "{{ nginx_src_path }}"
    remote_src: yes

- name: configure nginx
  become: yes
  shell: "./configure --prefix={{ nginx_path }} --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-stream --with-ngx_http_proxy_module --with-ngx_http_ssl_module {{ nginx_debug_option }}"
  args:
    chdir: "{{ nginx_src_path }}/nginx-{{ nginx_version }}"

- name: make nginx
  make:
    chdir: "{{ nginx_src_path }}/{{ nginx_name }}-{{ nginx_version }}"

- name: make install nginx
  make:
    chdir: "{{ nginx_src_path }}/{{ nginx_name }}-{{ nginx_version }}"
    target: install
  become: yes
